use std::error::Error;

fn solve(input: Vec<String>) -> Result<(String, String), Box<dyn Error>> {
    Ok(("".to_string(), "".to_string()))
}
